@echo off
cd /d "c:\Users\spong\Documents\trae_projects\world-cup\flags"

ren "flag_墨西哥.png" "flag_Mexico.png"
ren "flag_南非.png" "flag_SouthAfrica.png"
ren "flag_韩国.png" "flag_SouthKorea.png"
ren "flag_捷克.png" "flag_Czech.png"
ren "flag_加拿大.png" "flag_Canada.png"
ren "flag_波黑.png" "flag_Bosnia.png"
ren "flag_卡塔尔.png" "flag_Qatar.png"
ren "flag_瑞士.png" "flag_Switzerland.png"
ren "flag_巴西.png" "flag_Brazil.png"
ren "flag_摩洛哥.png" "flag_Morocco.png"
ren "flag_海地.png" "flag_Haiti.png"
ren "flag_苏格兰.png" "flag_Scotland.png"
ren "flag_美国.png" "flag_USA.png"
ren "flag_巴拉圭.png" "flag_Paraguay.png"
ren "flag_澳大利亚.png" "flag_Australia.png"
ren "flag_土耳其.png" "flag_Turkey.png"
ren "flag_德国.png" "flag_Germany.png"
ren "flag_库拉索.png" "flag_Curacao.png"
ren "flag_科特迪瓦.png" "flag_CoteDIvoire.png"
ren "flag_厄瓜多尔.png" "flag_Ecuador.png"
ren "flag_荷兰.png" "flag_Netherlands.png"
ren "flag_日本.png" "flag_Japan.png"
ren "flag_瑞典.png" "flag_Sweden.png"
ren "flag_突尼斯.png" "flag_Tunisia.png"
ren "flag_比利时.png" "flag_Belgium.png"
ren "flag_埃及.png" "flag_Egypt.png"
ren "flag_伊朗.png" "flag_Iran.png"
ren "flag_新西兰.png" "flag_NewZealand.png"
ren "flag_西班牙.png" "flag_Spain.png"
ren "flag_佛得角.png" "flag_CapeVerde.png"
ren "flag_沙特.png" "flag_SaudiArabia.png"
ren "flag_乌拉圭.png" "flag_Uruguay.png"
ren "flag_法国.png" "flag_France.png"
ren "flag_塞内加尔.png" "flag_Senegal.png"
ren "flag_伊拉克.png" "flag_Iraq.png"
ren "flag_挪威.png" "flag_Norway.png"
ren "flag_阿根廷.png" "flag_Argentina.png"
ren "flag_阿尔及利亚.png" "flag_Algeria.png"
ren "flag_奥地利.png" "flag_Austria.png"
ren "flag_约旦.png" "flag_Jordan.png"
ren "flag_葡萄牙.png" "flag_Portugal.png"
ren "flag_民主刚果.png" "flag_DRCongo.png"
ren "flag_乌兹别克斯坦.png" "flag_Uzbekistan.png"
ren "flag_哥伦比亚.png" "flag_Colombia.png"
ren "flag_英格兰.png" "flag_England.png"
ren "flag_克罗地亚.png" "flag_Croatia.png"
ren "flag_加纳.png" "flag_Ghana.png"
ren "flag_巴拿马.png" "flag_Panama.png"

echo Done!
pause